= Fulcro Datomic
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

A library that provides injectable datomic database components for Fulcro web servers. Includes
migration support, and extended schema validation.

image:https://img.shields.io/clojars/v/fulcrologic/fulcro-datomic.svg[link=https://clojars.org/fulcrologic/fulcro-datomic]

Release: image:https://api.travis-ci.org/fulcro-web/fulcro-datomic.svg?branch=master[link=https://github.com/fulcro-web/fulcro-datomic/tree/master]
Snapshot: image:https://api.travis-ci.org/fulcro-web/fulcro-datomic.svg?branch=develop[link=https://github.com/fulcro-web/fulcro-datomic/tree/develop]

NOTE: NAVIS is discontinuing its use of Datomic in favor of straight SQL for internal business reasons. This library
will no longer be maintained. If you would like to become the maintainer of this library, please contact us via the
issue #6 on this repository.

== Learn more
- about link:docs/index.adoc#fulcro-datomic-docs[Fulcro Datomic]
- about link:http://fulcro-web.github.io/fulcro/index.html[Fulcro] & checkout the link:http://fulcro-web.github.io/fulcro/index.html[Documentation Reference]
- interactively with the link:http://fulcro-web.github.io/fulcro/guide.html[Fulcro Tutorial]

## Usage

The Fulcro TodoMVC full-stack implementation demonstrates the basics of this library. More documentation
coming soon.

## License

The MIT License (MIT)
Copyright © 2016 NAVIS
