= Untangled Datomic
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

A library that provides injectable datomic database components for Untangled web servers. Includes
migration support, and extended schema validation.

image:https://img.shields.io/clojars/v/navis/untangled-datomic.svg[link=https://clojars.org/navis/untangled-datomic]

Release: image:https://api.travis-ci.org/untangled-web/untangled-datomic.svg?branch=master[link=https://github.com/untangled-web/untangled-datomic/tree/master]
Snapshot: image:https://api.travis-ci.org/untangled-web/untangled-datomic.svg?branch=develop[link=https://github.com/untangled-web/untangled-datomic/tree/develop]

NOTE: NAVIS is discontinuing its use of Datomic in favor of straight SQL for internal business reasons. This library
will no longer be maintained. If you would like to become the maintainer of this library, please contact us via the
issue #6 on this repository.

== Learn more
- about link:docs/index.adoc#untangled-datomic-docs[Untangled Datomic]
- about link:http://untangled-web.github.io/untangled/index.html[Untangled] & checkout the link:http://untangled-web.github.io/untangled/index.html[Documentation Reference]
- interactively with the link:http://untangled-web.github.io/untangled/guide.html[Untangled Tutorial]

## Usage

The Untangled TodoMVC full-stack implementation demonstrates the basics of this library. More documentation
coming soon.

## License

The MIT License (MIT)
Copyright © 2016 NAVIS
