= Fulcro Datomic
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

IMPORTANT: This library contains largely obsolete features at this point. It was an early experiment in the history
of the Untangled ecosystem, and since there was some adoption it was brought forward. In general, it is recommended
that you hand-pick other libraries, such as conformity, for migrations and such.  

A library that provides injectable datomic database components for Fulcro web servers. Includes
migration support, and extended schema validation.

image:https://img.shields.io/clojars/v/fulcrologic/fulcro-datomic.svg[link=https://clojars.org/fulcrologic/fulcro-datomic]

Release: image:https://api.travis-ci.org/fulcrologic/fulcro-datomic.svg?branch=master[link=https://github.com/fulcrologic/fulcro-datomic/tree/master]
Snapshot: image:https://api.travis-ci.org/fulcrologic/fulcro-datomic.svg?branch=develop[link=https://github.com/fulcrologic/fulcro-datomic/tree/develop]

== Learn more
- about link:docs/index.adoc#fulcro-datomic-docs[Fulcro Datomic]
- about link:http://fulcrologic.github.io/index.html[Fulcro] 

## Usage

The Fulcro TodoMVC full-stack implementation demonstrates the basics of this library. More documentation
coming soon.

## License

The MIT License (MIT)
Copyright © 2016 NAVIS
Copyright © 2017 Fulcrologic
