= Fulcro Datomic
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

== DEPRECATED

This library is no longer maintained. At the time of its inception there were limited solutions for the
features it provided, but now there are reasonable alternatives for most of the internal features.

- The experimental schema validation is much better implemented with Clojure Spec
- Migrations are still a weak point in Datomic, but http://github.com/rkneufeld/conformity[Conformity] seems reasonable
- https://github.com/Yuppiechef/datomic-schema[Datomic Schema] is a library that can make your schema look a little nicer in code.


== Overview

A library that provides injectable datomic database components for Fulcro web servers. Includes
migration support, and extended schema validation.

image:https://img.shields.io/clojars/v/fulcrologic/fulcro-datomic.svg[link=https://clojars.org/fulcrologic/fulcro-datomic]

Release: image:https://api.travis-ci.org/fulcrologic/fulcro-datomic.svg?branch=master[link=https://github.com/fulcrologic/fulcro-datomic/tree/master]
Snapshot: image:https://api.travis-ci.org/fulcrologic/fulcro-datomic.svg?branch=develop[link=https://github.com/fulcrologic/fulcro-datomic/tree/develop]

== Learn more
- about link:docs/index.adoc#fulcro-datomic-docs[Fulcro Datomic]
- about link:http://fulcrologic.github.io/index.html[Fulcro] 

## Usage

The Fulcro TodoMVC full-stack implementation demonstrates the basics of this library. More documentation
coming soon.

## License

The MIT License (MIT)
Copyright © 2016 NAVIS
Copyright © 2017 Fulcrologic
