= Untangled Datomic Docs
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement!:
:toclevels: 3
:sectlinks:
:sectanchors:
:sectnums:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[]
toc::[]
endif::[]

The Untangled Datomic library includes a few useful additions that make it easier to integrate one or more Datomic
databases as persistent storage:

- A configurable database component
- Schema and migration support
- Experimental schema rule enforcement for additional referential integrity checks

== Injecting and configuring database(s)

TODO

= Schema support

The schema support in Untangled Datomic is a fork of Yuppiechef's Datomic Schema with additions for experimental additional
schema enforcements.

== Migrations

== Validated transactions (EXPERIMENTAL)

The library comes with a function called `vtransact`. It works just like Datomic's `transact`, but enforces the additional
schema constraints. This function should be considered experimental. We'd be interested in feedback.
